#!/usr/bin/env bash
# Regenerates src/baseline.bock from tools/examples-exec-baseline.txt.
#
# WHY THIS EXISTS
# ---------------
# Bock's v1 stdlib has no file-read surface (filesystem/stdin effects are
# reserved for v1.x), so the tool cannot open the baseline file at runtime.
# Instead, this script snapshots the file verbatim into a generated Bock
# module (`module baseline`) as a List[String] — one element per line —
# and the tool does all real parsing/aggregation/rendering in Bock.
#
# Run from anywhere:
#   tools/examples-matrix/sync-baseline.sh
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
SRC_FILE="$REPO_ROOT/tools/examples-exec-baseline.txt"
OUT_FILE="$SCRIPT_DIR/src/baseline.bock"

if [[ ! -f "$SRC_FILE" ]]; then
  echo "error: $SRC_FILE not found" >&2
  exit 2
fi

{
  echo '//! AUTO-GENERATED by sync-baseline.sh — DO NOT EDIT BY HAND.'
  echo '//!'
  echo '//! Verbatim snapshot of `tools/examples-exec-baseline.txt`, one list'
  echo '//! element per line (tabs encoded as `\t`). Regenerate with:'
  echo '//!   tools/examples-matrix/sync-baseline.sh'
  echo ''
  echo 'module baseline'
  echo ''
  echo '/// Repo-relative path of the dataset this snapshot was taken from.'
  echo '@context("Provenance: repo-relative path of the snapshotted dataset, for the report header.")'
  echo 'public fn baseline_source() -> String {'
  echo '  "tools/examples-exec-baseline.txt"'
  echo '}'
  echo ''
  echo '/// The raw lines of the baseline file, verbatim.'
  echo '@context("Generated data, not logic: the verbatim lines of tools/examples-exec-baseline.txt, snapshotted because Bock v1 has no file-read surface. Regenerate via sync-baseline.sh; never edit by hand.")'
  echo 'public fn baseline_lines() -> List[String] {'
  echo '  ['
  # Escape, in order: backslash, double-quote, dollar (blocks ${ interpolation),
  # then encode literal tabs as \t. All four escapes are in Bock's lexer set.
  sed -e 's/\\/\\\\/g' -e 's/"/\\"/g' -e 's/\$/\\$/g' -e "s/\t/\\\\t/g" "$SRC_FILE" \
    | sed -e 's/^/    "/' -e 's/$/",/'
  echo '  ]'
  echo '}'
} > "$OUT_FILE"

echo "wrote $OUT_FILE ($(wc -l < "$SRC_FILE") source lines)"
